# -*- coding: utf-8 -*-
"""Digital_Twin_Driven_DQN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7TN3R_x31jX57exUHowEFaCjkCL6xKq
"""

#Digital Twin-Driven DQN for UAV-Assisted IoT Data Collection
#=============================================================

#A UAV flies a circular path and collects data from 10 ground sensors.
#Goal: keep AoI (how stale the data is) low across all sensors.

#The key idea: we maintain a Digital Twin of the UAV and its environment
#that stays in sync with the real UAV. The DQN trains inside this twin,
#and the twin continuously corrects its own parameters from real measurements.

#Components:
 # PhysicalUAVStub  ->  stand-in for the real UAV (has GPS noise, channel fading)
 # DigitalTwin      ->  virtual replica that syncs with the physical UAV
 #   KalmanFilter1D ->  fuses noisy position and path-loss readings
 #   DTCalibrator   ->  estimates path-loss exponent online using RLS
 #   FaultDetector  ->  catches anomalies in telemetry (GPS spoofing, FDI attacks)
 # MultiHeadDQN     ->  neural net with two heads: pick sensor + pick speed
 # Agent            ->  DQN with epsilon-greedy and a target network
 # RealEnv          ->  skeleton to plug in real hardware later

# Training and deployment flow:
#  Phase 1  ->  agent trains entirely inside the digital twin
#  Phase 2  ->  meanwhile, twin calibrates itself from physical telemetry
#  Phase 3  ->  trained policy runs on the physical UAV stub
#  Phase 4  ->  twin keeps calibrating as the UAV flies
#=============================================================

import math
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from collections import deque
from typing import List
import os
from PIL import Image
from google.colab import files

# ─────────────────────────────────────────────────────────────────
# Physical constants and simulation settings
# ─────────────────────────────────────────────────────────────────
NUM_NODES        = 10
BASE_ALTITUDE    = 100.0        # UAV flight altitude in metres
UAV_RADIUS       = 400.0        # radius of the circular flight path in metres
MAX_AOI          = 20.0         # AoI is capped at this value for each sensor
PKT_ARRIVAL_P    = 0.7          # probability a new packet arrives at a sensor each step
MAX_QUEUE_LEN    = 40           # max packets sitting in a sensor queue
A_PARAM          = 20.0         # 'a' in the LoS probability sigmoid
B_PARAM          = 0.3          # 'b' in the LoS probability sigmoid
ETA_LOS          = 1.0          # extra attenuation under LoS conditions (dB)
ETA_NLOS         = 20.0         # extra attenuation under NLoS conditions (dB)
FC               = 2e9          # carrier frequency in Hz
VC               = 3e8          # speed of light in m/s
WAVELENGTH       = VC / FC      # wavelength in metres
PKT_LOSS_THRESH  = -120.0       # path-loss threshold; below this = bad channel (dB)
VELOCITY_TABLE   = np.linspace(5, 30, 15)  # 15 discrete speeds the UAV can choose (m/s)
TIMESTEP_DUR     = 1.0          # how many seconds one decision step covers

# Noise parameters — these are what make the real world differ from the twin
MEASUREMENT_NOISE_STD = 3.0     # sensor noise on path-loss readings (dB)
POSITION_NOISE_STD    = 2.0     # GPS position error (metres)
CHANNEL_FADE_STD      = 2.0     # random fading on top of the path-loss model (dB)
TRUE_PATH_LOSS_EXP    = 2.8     # real path-loss exponent; twin starts at 2.0 and learns


# ═══════════════════════════════════════════════════════════════
# 1-D Kalman filter
# Used to clean up noisy position and path-loss measurements
# ═══════════════════════════════════════════════════════════════
class KalmanFilter1D:
    """
    Minimal Kalman filter for a single scalar quantity.

    Every time a new noisy reading arrives from the UAV, this filter
    blends the current estimate with the measurement based on how
    much we trust each one, and returns a cleaner estimate.

    x  ->  current estimate of the value
    P  ->  how uncertain we are about x (variance)
    Q  ->  how much the true value drifts each step (process noise)
    R  ->  how noisy the sensor is (measurement noise)
    """
    def __init__(self, process_var: float = 0.5, meas_var: float = 9.0,
                 init_val: float = 0.0):
        self.x = init_val    # initial guess
        self.P = 10.0        # start very uncertain
        self.Q = process_var
        self.R = meas_var

    def update(self, measurement: float) -> float:
        # predict: uncertainty grows a little each step
        self.P = self.P + self.Q
        # update: blend measurement into estimate using Kalman gain
        K = self.P / (self.P + self.R)
        self.x = self.x + K * (measurement - self.x)
        self.P = (1 - K) * self.P
        return self.x


# ═══════════════════════════════════════════════════════════════
# Digital Twin calibrator
# Estimates the path-loss exponent alpha online from real data
# ═══════════════════════════════════════════════════════════════
class DTCalibrator:
    """
    Recursive least-squares (RLS) estimator for the path-loss exponent.

    Simplified path-loss model:
        PL(d) = 20*log10(4*pi*d/lambda) + alpha * 10*log10(d)

    Alpha depends on the environment (terrain, obstacles, altitude).
    The twin starts with alpha=2.0 but the real value is 2.8.
    Each new measurement nudges alpha closer to the true value.

    forgetting  ->  older data matters less over time (lambda < 1)
    """
    def __init__(self, alpha_init: float = 2.0, forgetting: float = 0.98):
        self.alpha  = alpha_init   # current estimate of the path-loss exponent
        self.P_rls  = 100.0       # RLS variance, starts high (very uncertain)
        self.lam    = forgetting   # forgetting factor

    def update(self, distance_m: float, measured_loss_db: float) -> float:
        """Take one (distance, measured path-loss) pair and update alpha."""
        if distance_m < 1.0:
            return self.alpha

        d_log    = 10.0 * math.log10(distance_m)
        # free-space loss with no environment component
        fs_loss  = 20.0 * math.log10(max(4 * math.pi * distance_m / WAVELENGTH, 1e-9))
        # what alpha*d_log must explain
        residual = measured_loss_db - fs_loss

        phi         = d_log
        K_rls       = (self.P_rls * phi) / (self.lam + phi * self.P_rls * phi)
        error       = residual - phi * self.alpha
        self.alpha += K_rls * error
        self.P_rls  = (1.0 / self.lam) * (1.0 - K_rls * phi) * self.P_rls
        # keep alpha in a physically sensible range
        self.alpha  = float(np.clip(self.alpha, 1.5, 5.0))
        return self.alpha


# ═══════════════════════════════════════════════════════════════
# Anomaly detector
# Watches for suspicious gaps between twin predictions and real readings
# ═══════════════════════════════════════════════════════════════
class FaultDetector:
    """
    Statistical test for anomalies in UAV telemetry.

    If the measured path-loss is way off from what the twin predicted,
    something unusual happened — likely one of:
      - GPS spoofing attack (UAV thinks it's somewhere else)
      - False Data Injection (FDI) into sensor readings
      - Hardware fault in a sensor

    Method: z-score on a sliding window of residuals.
    Raises a flag when |z| > threshold_sigma.
    """
    def __init__(self, window: int = 10, threshold_sigma: float = 3.0):
        self.residuals     = deque(maxlen=window)
        self.threshold     = threshold_sigma
        self.anomaly_flags: List[bool] = []

    def check(self, predicted_pl: float, measured_pl: float) -> bool:
        """Returns True if an anomaly is detected."""
        res = measured_pl - predicted_pl
        self.residuals.append(res)
        if len(self.residuals) < 3:
            self.anomaly_flags.append(False)
            return False
        mu    = float(np.mean(self.residuals))
        sigma = max(float(np.std(self.residuals)), 0.1)
        z     = abs((res - mu) / sigma)
        flag  = bool(z > self.threshold)
        self.anomaly_flags.append(flag)
        return flag


# ═══════════════════════════════════════════════════════════════
# Physical UAV stub
# Simulates the real world with noise and imperfections
# ═══════════════════════════════════════════════════════════════
class PhysicalUAVStub:
    """
    Stands in for the actual UAV hardware (or a high-fidelity emulator).

    Key differences from the digital twin:
      - GPS position has Gaussian noise
      - Path-loss uses the real exponent 2.8, not the twin's initial guess of 2.0
      - Measurements include random fading and sensor noise

    This is what the twin must sync against and calibrate from.
    In real deployment, replace this class with actual hardware calls.
    """
    def __init__(self, num_nodes: int = NUM_NODES, seed: int = 7):
        self.num_nodes = num_nodes
        rng = random.Random(seed)
        np.random.seed(seed + 1)

        # sensor positions — the twin doesn't know these exactly at first
        self._node_xy = []
        for _ in range(num_nodes):
            r  = UAV_RADIUS * math.sqrt(rng.random())
            th = rng.uniform(0, 2 * math.pi)
            self._node_xy.append((r * math.cos(th), r * math.sin(th)))

        # circular flight path
        theta        = np.linspace(0, 2 * math.pi, 361)
        self._uav_x  = UAV_RADIUS * np.cos(theta)
        self._uav_y  = UAV_RADIUS * np.sin(theta)
        self._t      = 0
        self._aoi    = np.full(num_nodes, MAX_AOI, dtype=np.float32)
        self._queues = [deque() for _ in range(num_nodes)]

        # seed initial packets in queues
        for i in range(num_nodes):
            if rng.random() < PKT_ARRIVAL_P:
                for _ in range(20):
                    self._queues[i].append(1)

    def get_telemetry(self) -> dict:
        """
        Returns a noisy telemetry packet — what the UAV actually transmits to the twin.
        Both position and path-loss readings are corrupted by noise.
        """
        true_x = self._uav_x[self._t]
        true_y = self._uav_y[self._t]

        # GPS noise
        meas_x = true_x + np.random.normal(0, POSITION_NOISE_STD)
        meas_y = true_y + np.random.normal(0, POSITION_NOISE_STD)

        # path-loss with real physics plus noise
        measured_pl = []
        for i in range(self.num_nodes):
            nx, ny = self._node_xy[i]
            d = math.sqrt((true_x - nx)**2 + (true_y - ny)**2 + BASE_ALTITUDE**2)
            d = max(d, 1.0)
            # true physics: real exponent 2.8
            pl_true = (20 * math.log10(max(4 * math.pi * d / WAVELENGTH, 1e-9))
                       + TRUE_PATH_LOSS_EXP * 10 * math.log10(d))
            # add sensor noise and random channel fading
            pl_meas = (pl_true
                       + np.random.normal(0, MEASUREMENT_NOISE_STD)
                       + np.random.normal(0, CHANNEL_FADE_STD))
            measured_pl.append(pl_meas)

        return {
            "t":         self._t,
            "pos_x":     meas_x,
            "pos_y":     meas_y,
            "aoi":       self._aoi.copy(),
            "path_loss": np.array(measured_pl, dtype=np.float32),
            "node_xy":   list(self._node_xy),
        }

    def execute_action(self, node_idx: int, velocity_idx: int) -> dict:
        """Runs an action on the physical UAV and returns the resulting telemetry."""
        velocity   = VELOCITY_TABLE[velocity_idx]
        steps      = max(1, int(velocity * TIMESTEP_DUR))
        self._t    = (self._t + steps) % len(self._uav_x)

        tel = self.get_telemetry()
        pl  = tel["path_loss"]

        # serve the selected sensor
        if self._queues[node_idx]:
            self._queues[node_idx].popleft()
            if pl[node_idx] < PKT_LOSS_THRESH:
                # bad channel: reception failed, AoI gets worse
                self._aoi[node_idx] = min(self._aoi[node_idx] + 1, MAX_AOI)
            else:
                # good channel: data received, AoI resets
                self._aoi[node_idx] = 1.0
        else:
            # nothing in queue
            self._aoi[node_idx] = min(self._aoi[node_idx] + 1, MAX_AOI)

        # age AoI for all other sensors
        for i in range(self.num_nodes):
            if i == node_idx:
                continue
            if random.random() < PKT_ARRIVAL_P:
                self._queues[i].append(1)
            self._aoi[i] = min(self._aoi[i] + 1, MAX_AOI)
            while len(self._queues[i]) > MAX_QUEUE_LEN:
                self._queues[i].popleft()

        return self.get_telemetry()


# ═══════════════════════════════════════════════════════════════
# Digital Twin — the heart of the system
# ═══════════════════════════════════════════════════════════════
class DigitalTwin:
    """
    The digital twin: a living virtual copy of the UAV and its environment.

    What makes it more than a plain simulator:
      (A) maintains a belief state fused from noisy telemetry via Kalman filters
      (B) calibrates its own path-loss model online as new data arrives
      (C) flags anomalies in telemetry (GPS spoofing, FDI attacks)
      (D) exposes a Gym-style interface so DRL can train inside it
      (E) accepts sync packets from the physical UAV and updates itself

    State vector (length = NUM_NODES + 3):
        [AoI_0 ... AoI_{N-1},  path_loss_to_selected_sensor,  uav_x,  uav_y]
    """

    def __init__(self, num_nodes: int = NUM_NODES, seed: int = 42):
        self.num_nodes = num_nodes
        self.state_dim = num_nodes + 3

        random.seed(seed)
        np.random.seed(seed)

        # twin's initial belief about sensor positions (may be off from truth)
        self._node_xy = self._place_nodes()

        # UAV trajectory model
        theta        = np.linspace(0, 2 * math.pi, 361)
        self._uav_x  = UAV_RADIUS * np.cos(theta)
        self._uav_y  = UAV_RADIUS * np.sin(theta)

        # Kalman-filtered position estimate
        self._est_x = self._uav_x[0]
        self._est_y = self._uav_y[0]
        self._kf_x  = KalmanFilter1D(process_var=1.0,
                                      meas_var=POSITION_NOISE_STD**2,
                                      init_val=self._uav_x[0])
        self._kf_y  = KalmanFilter1D(process_var=1.0,
                                      meas_var=POSITION_NOISE_STD**2,
                                      init_val=self._uav_y[0])
        # separate Kalman filter for each sensor's path-loss
        self._kf_pl = [
            KalmanFilter1D(process_var=0.5,
                           meas_var=MEASUREMENT_NOISE_STD**2,
                           init_val=-80.0)
            for _ in range(num_nodes)
        ]

        # path-loss calibrator (starts at alpha=2.0, real value is 2.8)
        self.calibrator    = DTCalibrator(alpha_init=2.0)
        self._alpha        = self.calibrator.alpha

        # anomaly detector
        self.fault_detector = FaultDetector(window=10, threshold_sigma=3.0)
        self.anomaly_count  = 0
        self.sync_count     = 0
        self.alpha_history  = [self._alpha]

        self.reset()

    def _place_nodes(self):
        """Twin's initial guess for sensor positions (different seed from physical UAV)."""
        xy = []
        for _ in range(self.num_nodes):
            r  = UAV_RADIUS * math.sqrt(random.random())
            th = random.uniform(0, 2 * math.pi)
            xy.append((r * math.cos(th), r * math.sin(th)))
        return xy

    # ── Gym interface ──────────────────────────────────────────────
    def reset(self):
        """Reset the twin's internal state for a new episode."""
        self._queues = [deque() for _ in range(self.num_nodes)]
        self._aoi    = np.full(self.num_nodes, MAX_AOI, dtype=np.float32)
        self._t      = 0
        for i in range(self.num_nodes):
            if random.random() < PKT_ARRIVAL_P:
                for _ in range(20):
                    self._queues[i].append(1)
        return self._get_state(selected_node=0)

    def step(self, node_idx: int, velocity_idx: int):
        """Take one simulation step inside the twin."""
        velocity  = VELOCITY_TABLE[velocity_idx]
        steps_fwd = max(1, int(velocity * TIMESTEP_DUR))
        self._t   = (self._t + steps_fwd) % len(self._uav_x)

        # pull UAV position from the circular trajectory
        self._est_x = self._uav_x[self._t]
        self._est_y = self._uav_y[self._t]

        pl = self._compute_pathloss_calibrated()
        self._serve_node(node_idx, pl)
        self._age_other_nodes(node_idx)

        reward = -float(np.mean(self._aoi))    # negative AoI = we want to minimise it
        info   = {
            "pathloss":      pl,
            "aoi":           self._aoi.copy(),
            "alpha":         self._alpha,
            "anomaly_count": self.anomaly_count,
        }
        return self._get_state(node_idx), reward, False, info

    # ── Bidirectional synchronisation ─────────────────────────────
    def synchronise(self, telemetry: dict):
        """
        Receive a telemetry packet from the physical UAV and update the twin.

        This is the core of what makes it a real digital twin.
        Every time the physical UAV sends data, we do six things:

        1. clean up the noisy GPS position with the Kalman filter
        2. clean up each sensor's noisy path-loss reading
        3. use those cleaned readings to refine our estimate of alpha (RLS)
        4. compare twin prediction vs measurement to catch anomalies
        5. softly blend the physical AoI readings into the twin's belief
        6. slowly correct the twin's belief about sensor positions
        """
        self.sync_count += 1

        # 1. filter noisy GPS position
        self._est_x = self._kf_x.update(telemetry["pos_x"])
        self._est_y = self._kf_y.update(telemetry["pos_y"])

        # 2. filter each sensor's path-loss reading
        pl_meas = telemetry["path_loss"]
        pl_est  = []
        for i in range(self.num_nodes):
            est = self._kf_pl[i].update(float(pl_meas[i]))
            pl_est.append(est)

        # 3. update alpha using the cleaned path-loss and estimated distances
        for i in range(self.num_nodes):
            nx, ny = self._node_xy[i]
            d = math.sqrt((self._est_x - nx)**2 +
                          (self._est_y - ny)**2 + BASE_ALTITUDE**2)
            self._alpha = self.calibrator.update(d, pl_est[i])
        self.alpha_history.append(self._alpha)

        # 4. check for anomalies: compare what twin expected vs what arrived
        pl_dt_pred = self._compute_pathloss_calibrated()
        for i in range(self.num_nodes):
            if self.fault_detector.check(pl_dt_pred[i], float(pl_meas[i])):
                self.anomaly_count += 1

        # 5. soft blend: 70% trust old twin belief, 30% trust physical reading
        self._aoi = 0.7 * self._aoi + 0.3 * telemetry["aoi"]

        # 6. nudge sensor position beliefs slowly toward reported values
        if "node_xy" in telemetry:
            for i, (nx, ny) in enumerate(telemetry["node_xy"]):
                ox, oy = self._node_xy[i]
                # move 10% toward the physical reading each sync
                self._node_xy[i] = (0.9 * ox + 0.1 * nx,
                                    0.9 * oy + 0.1 * ny)

    # ── Path-loss with the calibrated model ───────────────────────
    def _compute_pathloss_calibrated(self):
        """Compute path-loss to all sensors using the current alpha estimate."""
        pl = []
        for i in range(self.num_nodes):
            nx, ny = self._node_xy[i]
            d = math.sqrt((self._est_x - nx)**2 +
                          (self._est_y - ny)**2 + BASE_ALTITUDE**2)
            d = max(d, 1.0)
            loss = (20 * math.log10(max(4 * math.pi * d / WAVELENGTH, 1e-9))
                    + self._alpha * 10 * math.log10(d))
            pl.append(loss)
        return pl

    def _serve_node(self, node_idx: int, pathloss: list):
        """Collect a packet from the selected sensor and update its AoI."""
        if random.random() < PKT_ARRIVAL_P:
            self._queues[node_idx].append(1)
        if self._queues[node_idx]:
            self._queues[node_idx].popleft()
            if pathloss[node_idx] < PKT_LOSS_THRESH:
                # channel too weak — reception failed
                self._aoi[node_idx] = min(self._aoi[node_idx] + 1, MAX_AOI)
            else:
                # successful delivery — AoI resets to 1
                self._aoi[node_idx] = 1.0
        else:
            # queue was empty
            self._aoi[node_idx] = min(self._aoi[node_idx] + 1, MAX_AOI)
        while len(self._queues[node_idx]) > MAX_QUEUE_LEN:
            self._queues[node_idx].popleft()

    def _age_other_nodes(self, selected: int):
        """Sensors that weren't visited this step get one unit older."""
        for i in range(self.num_nodes):
            if i == selected:
                continue
            if random.random() < PKT_ARRIVAL_P:
                self._queues[i].append(1)
            self._aoi[i] = min(self._aoi[i] + 1, MAX_AOI)
            while len(self._queues[i]) > MAX_QUEUE_LEN:
                self._queues[i].popleft()

    def _get_state(self, selected_node: int):
        """Build the current state vector."""
        pl    = self._compute_pathloss_calibrated()
        state = np.zeros(self.state_dim, dtype=np.float32)
        state[:self.num_nodes]    = self._aoi
        state[self.num_nodes]     = pl[selected_node]
        state[self.num_nodes + 1] = self._est_x
        state[self.num_nodes + 2] = self._est_y
        return state


# ═══════════════════════════════════════════════════════════════
# Neural network with two output heads
# ═══════════════════════════════════════════════════════════════
class MultiHeadDQN(nn.Module):
    """
    Shared backbone that feeds into two separate heads:
      head_nodes  ->  Q-values over which sensor to visit
      head_vel    ->  Q-values over which speed to fly at

    Both decisions share the same internal representation,
    which makes learning more efficient than two separate networks.
    """
    def __init__(self, state_dim: int, num_nodes: int,
                 num_velocities: int, hidden: int = 256):
        super().__init__()
        self.shared = nn.Sequential(
            nn.Linear(state_dim, hidden), nn.ReLU(),
            nn.Linear(hidden, hidden),   nn.ReLU(),
        )
        self.head_nodes = nn.Linear(hidden, num_nodes)
        self.head_vel   = nn.Linear(hidden, num_velocities)

    def forward(self, x):
        h = self.shared(x)
        return self.head_nodes(h), self.head_vel(h)


# ═══════════════════════════════════════════════════════════════
# Experience replay buffer
# ═══════════════════════════════════════════════════════════════
class ReplayBuffer:
    """
    Circular buffer that stores past (state, action, reward) transitions.
    When full, oldest entries get overwritten.
    Sampling random batches breaks correlations in the training data.
    """
    def __init__(self, max_size: int = 100_000):
        self.storage  = []
        self.max_size = max_size
        self.ptr      = 0

    def add(self, s, s2, node, vel, reward):
        t = (s, s2, node, vel, reward)
        if len(self.storage) < self.max_size:
            self.storage.append(t)
        else:
            self.storage[self.ptr] = t
            self.ptr = (self.ptr + 1) % self.max_size

    def sample(self, batch_size: int):
        idx = np.random.randint(0, len(self.storage), size=batch_size)
        s, s2, n, v, r = zip(*[self.storage[i] for i in idx])
        return (
            torch.FloatTensor(np.array(s)),
            torch.FloatTensor(np.array(s2)),
            torch.LongTensor(np.array(n)),
            torch.LongTensor(np.array(v)),
            torch.FloatTensor(np.array(r)).unsqueeze(1),
        )

    def __len__(self):
        return len(self.storage)


# ═══════════════════════════════════════════════════════════════
# DQN agent
# ═══════════════════════════════════════════════════════════════
class Agent:
    """
    DQN agent with epsilon-greedy exploration and a target network.

    We keep two copies of the network:
      Q        ->  the online network that gets updated every step
      Q_target ->  a lagged copy used to compute stable training targets

    The target network is soft-updated toward Q each step (tau=0.005),
    which stabilises training compared to copying weights all at once.
    """
    def __init__(self, state_dim: int, num_nodes: int, num_velocities: int,
                 lr: float = 1e-3, gamma: float = 0.99, tau: float = 0.005):
        self.num_nodes      = num_nodes
        self.num_velocities = num_velocities
        self.gamma          = gamma
        self.tau            = tau

        self.Q        = MultiHeadDQN(state_dim, num_nodes, num_velocities)
        self.Q_target = MultiHeadDQN(state_dim, num_nodes, num_velocities)
        self.Q_target.load_state_dict(self.Q.state_dict())
        self.optimizer = optim.Adam(self.Q.parameters(), lr=lr)

    def select_action(self, state: np.ndarray, epsilon: float):
        """With probability epsilon pick randomly, otherwise pick the best action."""
        if random.random() < epsilon:
            return (random.randint(0, self.num_nodes - 1),
                    random.randint(0, self.num_velocities - 1))
        with torch.no_grad():
            s = torch.FloatTensor(state).unsqueeze(0)
            qn, qv = self.Q(s)
            return torch.argmax(qn).item(), torch.argmax(qv).item()

    def train_step(self, buf: ReplayBuffer, batch_size: int = 100):
        """One gradient update using a random batch from the replay buffer."""
        if len(buf) < batch_size:
            return None     # not enough data yet

        s, s2, n, v, r = buf.sample(batch_size)

        # Q-values for the actions that were actually taken
        qn, qv  = self.Q(s)
        q_n_cur = qn.gather(1, n.unsqueeze(1)).squeeze(1)
        q_v_cur = qv.gather(1, v.unsqueeze(1)).squeeze(1)

        # Bellman targets from the target network
        with torch.no_grad():
            qn2, qv2 = self.Q_target(s2)
            tgt_n    = r.squeeze() + self.gamma * qn2.max(1)[0]
            tgt_v    = r.squeeze() + self.gamma * qv2.max(1)[0]

        loss = nn.MSELoss()(q_n_cur, tgt_n) + nn.MSELoss()(q_v_cur, tgt_v)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        # soft update: nudge target network slightly toward online network
        for tp, p in zip(self.Q_target.parameters(), self.Q.parameters()):
            tp.data.copy_(self.tau * p.data + (1 - self.tau) * tp.data)

        return loss.item()

    def save(self, path: str = "dt_dqn.pth"):
        torch.save(self.Q.state_dict(), path)

    def load(self, path: str = "dt_dqn.pth"):
        self.Q.load_state_dict(torch.load(path, weights_only=True))
        self.Q_target.load_state_dict(self.Q.state_dict())


# ═══════════════════════════════════════════════════════════════
# Real hardware skeleton
# Fill this in when you're ready to deploy on an actual UAV
# ═══════════════════════════════════════════════════════════════
class RealEnv:
    """
    Same interface as DigitalTwin.step() / reset().
    The trained agent works here without any changes.

    To connect to a real UAV, implement reset() and step() below.
    """
    def __init__(self):
        self.state_dim = NUM_NODES + 3
        self.num_nodes = NUM_NODES
        self.num_vel   = len(VELOCITY_TABLE)

    def reset(self) -> np.ndarray:
        raise NotImplementedError("Connect real UAV hardware here")

    def step(self, node_idx: int, velocity_idx: int):
        raise NotImplementedError("Connect real UAV hardware here")


# ═══════════════════════════════════════════════════════════════
# Main training and deployment pipeline
# ═══════════════════════════════════════════════════════════════
def run_dt_driven_pipeline(
    max_episodes:  int   = 500,
    max_timesteps: int   = 30,
    batch_size:    int   = 100,
    epsilon_start: float = 1.0,
    epsilon_min:   float = 0.01,
    epsilon_decay: float = 0.995,
    sync_interval: int   = 5,       # sync twin with physical UAV every N steps
    save_path:     str   = "dt_dqn.pth",
):
    """
    Four-phase pipeline:

    Phases 1 and 2 run together:
      - agent trains inside the digital twin
      - every sync_interval steps, the twin gets a telemetry packet from the physical UAV
      - each sync corrects alpha and nudges sensor position beliefs toward reality

    Phase 3:
      - trained policy runs on the PhysicalUAVStub
      - twin keeps syncing in the background
    """
    twin  = DigitalTwin(num_nodes=NUM_NODES)
    phys  = PhysicalUAVStub(num_nodes=NUM_NODES)
    agent = Agent(twin.state_dim, NUM_NODES, len(VELOCITY_TABLE))
    buf   = ReplayBuffer()

    epsilon      = epsilon_start
    episode_aoi  = []
    episode_loss = []
    alpha_trace  = []

    print("=" * 60)
    print("  Digital Twin-Driven DRL Pipeline")
    print(f"  episodes={max_episodes}  steps/ep={max_timesteps}")
    print(f"  true alpha={TRUE_PATH_LOSS_EXP}, twin starts at alpha=2.0")
    print("=" * 60)

    for ep in range(max_episodes):
        state       = twin.reset()
        ep_aoi      = 0.0
        ep_loss     = 0.0
        ep_loss_cnt = 0

        for t in range(max_timesteps):
            node, vel = agent.select_action(state, epsilon)

            # step inside the twin
            next_state, reward, _, info = twin.step(node, vel)
            buf.add(state, next_state, node, vel, reward)

            # pull physical telemetry and sync the twin
            if t % sync_interval == 0:
                tel = phys.get_telemetry()
                twin.synchronise(tel)

            loss = agent.train_step(buf, batch_size)
            ep_aoi += float(np.mean(info["aoi"]))
            if loss is not None:
                ep_loss     += loss
                ep_loss_cnt += 1
            state = next_state

        epsilon   = max(epsilon_min, epsilon * epsilon_decay)
        avg_aoi   = ep_aoi / max_timesteps
        avg_loss  = ep_loss / max(ep_loss_cnt, 1)
        episode_aoi.append(avg_aoi)
        episode_loss.append(avg_loss)
        alpha_trace.append(twin.calibrator.alpha)

        if (ep + 1) % 50 == 0:
            print(f"  ep {ep+1:4d}/{max_episodes} | "
                  f"avg AoI={avg_aoi:.3f} | "
                  f"loss={avg_loss:.5f} | "
                  f"alpha_hat={twin.calibrator.alpha:.3f} | "
                  f"eps={epsilon:.3f} | "
                  f"anomalies={twin.anomaly_count}")

    agent.save(save_path)
    print(f"\nmodel saved -> {save_path}")
    print(f"total sync ops : {twin.sync_count}")
    print(f"total anomalies: {twin.anomaly_count}")
    print(f"final alpha_hat={twin.calibrator.alpha:.3f}  (true={TRUE_PATH_LOSS_EXP})")

    # Phase 3: test on the physical UAV stub
    print("\n-- Phase 3: deploy on Physical UAV --")
    deploy_aoi = []
    state = twin.reset()
    for t in range(100):
        node, vel = agent.select_action(state, epsilon=0.0)
        tel       = phys.execute_action(node, vel)
        twin.synchronise(tel)
        state = twin._get_state(node)
        deploy_aoi.append(float(np.mean(tel["aoi"])))
    print(f"  deployment avg AoI = {np.mean(deploy_aoi):.3f}")

    return agent, episode_aoi, episode_loss, alpha_trace, deploy_aoi

def convert_png_to_pdf_and_download(png_path, pdf_path):
    image = Image.open(png_path)
    # Ensure the image is in RGB mode before saving as PDF
    if image.mode == 'RGBA':
        image = image.convert('RGB')
    image.save(pdf_path, "PDF", resolution=100.0)
    print(f"Converted {png_path} to {pdf_path}")
    files.download(pdf_path)

# ═══════════════════════════════════════════════════════════════
# Plotting
# ═══════════════════════════════════════════════════════════════
def plot_results(episode_aoi, episode_loss, alpha_trace, deploy_aoi):
    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    fig.suptitle("DT-Driven DQN for UAV Resource Allocation",
                 fontsize=14, fontweight="bold")

    # (a) AoI convergence during training
    ax = axes[0, 0]
    ax.plot(episode_aoi, linewidth=1.5, color="steelblue")
    ax.set_xlabel("Episode")
    ax.set_ylabel("Average AoI")
    ax.set_title("(a) Training Convergence (DT Environment)")
    ax.grid(True, alpha=0.3)

    # (b) alpha calibration converging toward the true value
    ax = axes[0, 1]
    ax.plot(alpha_trace, linewidth=1.5, color="darkorange",
            label=r"$\hat{\alpha}$ (DT estimate)")
    ax.axhline(y=TRUE_PATH_LOSS_EXP, color="red", linestyle="--", linewidth=1.5,
               label=rf"True $\alpha={TRUE_PATH_LOSS_EXP}$")
    ax.set_xlabel("Episode")
    ax.set_ylabel(r"Path-Loss Exponent $\alpha$")
    ax.set_title("(b) Online DT Calibration via Bidirectional Sync")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # (c) training loss
    ax = axes[1, 0]
    ax.plot(episode_loss, linewidth=1.2, color="tomato")
    ax.set_xlabel("Episode")
    ax.set_ylabel("MSE Loss")
    ax.set_title("(c) DQN Training Loss")
    ax.grid(True, alpha=0.3)

    # (d) AoI when the learned policy runs on the physical UAV
    ax = axes[1, 1]
    ax.plot(deploy_aoi, linewidth=1.5, color="seagreen", label="Physical UAV")
    ax.axhline(y=np.mean(deploy_aoi), color="black", linestyle="--",
               label=f"Mean AoI = {np.mean(deploy_aoi):.2f}")
    ax.set_xlabel("Timestep")
    ax.set_ylabel("Average AoI")
    ax.set_title("(d) Policy Deployment on Physical UAV (Phase 3)")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    output_dir = "/mnt/user-data/outputs/"
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, "dt_dqn_results.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"plot saved -> {out_path}")
    plt.close()
    return out_path


# ═══════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    agent, ep_aoi, ep_loss, alpha_trace, deploy_aoi = run_dt_driven_pipeline(
        max_episodes  = 500,
        max_timesteps = 30,
        batch_size    = 100,
        sync_interval = 5,
    )
    png_path = plot_results(ep_aoi, ep_loss, alpha_trace, deploy_aoi)
    pdf_path = png_path.replace('.png', '.pdf')
    convert_png_to_pdf_and_download(png_path, pdf_path)